## NIST Incident Report (SOC / DFIR STYLE)

# Incident Report: File Integrity Violation Detected


# Incident Summary
On March 19, 2026, a file integrity monitoring alert was triggered on the Linux endpoint cloud-lab. The alert indicated unauthorized file modification and deletion activity within a monitored directory.

# Timeline of Events

Time
Event
21:19:19
Integrity checksum changed detected
21:20:22

# File deletion detected

Continuous
Rootcheck scans executed

# Detection Method

The incident was detected using:
Wazuh HIDS
Syscheck (File Integrity Monitoring)
Checksum comparison against baseline

# Incident Description

A monitored file located in /tmp was:
Created and baselined
Modified multiple times
Deleted shortly after
This behavior is consistent with:
Unauthorized file tampering
Potential attacker testing persistence or evasion

# Impact Assessment

No critical system files were affected
Activity occurred in a controlled lab environment
Demonstrates potential real-world attack behavior

# Root Cause

Simulated malicious activity from a test user to validate detection capabilities of Wazuh FIM.
# Response Actions (NIST Phases)
1. Detection & Analysis
Alerts generated by Wazuh dashboard
Events correlated using timestamps
2. Containment
Activity isolated within test environment
No lateral movement observed
3. Eradication
Malicious test file removed
System integrity verified
4. Recovery
System returned to baseline state
Monitoring confirmed normal activity

# Lessons Learned

FIM requires baseline before detection
Scan frequency impacts detection timing
Monitoring /tmp can generate high noise
Critical directories should be prioritized

# Recommendations

Monitor sensitive directories (/etc, /var)
Increase alert severity for critical file changes
Implement real-time monitoring where possible
Integrate with SIEM correlation rules

#MITRE ATT&CK Mapping

T1565.001 – Data Manipulation
T1070.004 – File Deletion
